# Hibernate properties
hibernate.connection.driver_class = org.postgresql.Driver
hibernate.connection.url = jdbc:postgresql://localhost:5432/postgres
hibernate.connection.username = postgres
hibernate.connection.password = sakura
hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql = true
hibernate.current_session_context_class = thread
hibernate.hbm2ddl.auto = update

# SQL queries
query.create.table=CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255), last_name VARCHAR(255), age TINYINT)
query.drop.table=DROP TABLE IF EXISTS users
query.delete.all=DELETE FROM users

# JDBC
jdbc.url = jdbc:postgresql://localhost:5432/postgres
jdbc.username = postgres
jdbc.password = sakura