# Hibernate properties
hibernate.connection.driver_class = org.postgresql.Driver
hibernate.connection.url = jdbc:postgresql://localhost:5432/Task1
hibernate.connection.username = postgres
hibernate.connection.password = sakura
hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql = true
hibernate.current_session_context_class = thread
hibernate.hbm2ddl.auto = update

# SQL queries
query.create.table=CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, name VARCHAR(50), last_name VARCHAR(50), age SMALLINT)
query.drop.table=DROP TABLE IF EXISTS users
query.delete.all=DELETE FROM users

# JDBC
jdbc.url = jdbc:postgresql://localhost:5432/Task1
jdbc.username = postgres
jdbc.password = sakura